### ISSUE TITLE
Create Endpoints

### ISSUE THREAD

**Issue by ritzmanndominic** [blerineberisha/uek223#5]

**Comment by blerinebee** [comment]
- CRUD endpoints for blog posts
        - createBlogPost (authorisation needed)
        - getAllBlogPosts (authorisation not needed)
        - updateBlogPost (authorisation needed)
        - deleteBlogPost (authorisation needed)
- CRUD endpoints for users
        - createUser (authorisation not needed)
        - getAllUsers (authorisation needed)
        - getSingleUser (authorisation needed)
        - updateUser (authorisation needed)
        - deleteUser (authorisation needed)
